<div>
    <h2 class="text-xl font-bold mb-3 pb-2 border-b">
        <?= __('Examples Introduction') ?>
    </h2>

    <p class="border border-yellow-300 bg-yellow-100 p-4 rounded-md">
        <?= __('The following examples are for inspiration only. Under no circumstances is it recommended to use these
        examples in a production environment. These examples are not optimized for responsiveness. Additional generic
        examples can be added via a Github Pull Request.') ?>
    </p>
</div>
