<?php declare(strict_types=1);
/**
 * Copyright © Willem Poortman 2021-present. All rights reserved.
 *
 * Please read the README and LICENSE files for more
 * details on copyrights and license information.
 */

/** @var \Magewirephp\MagewireExamples\Magewire\Reacticon $magewire */
$magewire = $block->getMagewire();
?>
<div id="reacticon" class="space-y-4">
    <h2 class="text-xl font-bold mb-3 pb-2 border-b">
        Counter - One
    </h2>

    <div class="flex justify-between items-center">
        <button class="btn btn-primary bg-green-500 hover:bg-green-700" wire:click="increment">
            <span>&plus;<?= $magewire->getInterval() ?></span>
        </button>

        <div class="border border-gray-500 px-4 py-2 rounded-md">
            <?= $magewire->getQuantity() ?>
        </div>

        <button class="btn btn-primary bg-yellow-500 hover:bg-yellow-700" wire:click="decrement">
            <span>&minus;<?= $magewire->getInterval() ?></span>
        </button>
    </div>
</div>
