<?php declare(strict_types=1);
/**
 * Copyright © Willem Poortman 2021-present. All rights reserved.
 *
 * Please read the README and LICENSE files for more
 * details on copyrights and license information.
 */

/** @var \Magewirephp\MagewireExamples\Magewire\Reacticon $magewire */
$magewire = $block->getMagewire();
?>
<div id="reacticon" class="space-y-4">
    <h2 class="text-xl font-bold mb-3 pb-2 border-b">
        Counter - Two
    </h2>

    <div class="flex justify-between items-center">
        <button class="btn btn-primary bg-green-500 hover:bg-green-700" wire:click="increment">
            <span>&plus;<?= $magewire->getInterval() ?></span>
        </button>

        <div class="border border-gray-500 px-4 py-2 rounded-md">
            <?= $magewire->getQuantity() ?>
        </div>

        <button class="btn btn-primary bg-yellow-500 hover:bg-yellow-700" wire:click="decrement">
            <span>&minus;<?= $magewire->getInterval() ?></span>
        </button>
    </div>

    <div x-data="{explanationVisible: <?= !$magewire->getMarkAsDone() ? 'false' : 'true' ?>}"
         class="flex-col space-y-4"
    >
        <label class="inline-flex items-center cursor-pointer" for="showReacticonConfigurationTwo">
            <input type="checkbox" id="showReacticonConfigurationTwo" x-on:click="explanationVisible = !explanationVisible"/>
            <span class="ml-4">Show configuration</span>
        </label>

        <div class="border border-gray-300 bg-gray-100 p-4 rounded-md space-y-4" x-show="explanationVisible">
            <div class="flex items-center">
                <label for="quantity" class="inline-block w-20 mr-6 text-right font-bold text-gray-600">
                    <?= __('Interval') ?>
                </label>

                <input type="number"
                       id="quantity"
                       placeholder="number"
                       class="form-input flex-1 outline-none"
                       wire:model="interval"
                />
            </div>
        </div>
    </div>
</div>
