<?php declare(strict_types=1);
/**
 * Copyright © Willem Poortman 2021-present. All rights reserved.
 *
 * Please read the README and LICENSE files for more
 * details on copyrights and license information.
 */

/** @var \Magewirephp\MagewireExamples\Magewire\DispatchEvents $magewire */
$magewire = $block->getMagewire();
?>
<div id="dispatch-events" class="space-y-4">
    <h2 class="text-xl font-bold mb-3 pb-2 border-b">
        <?= __('Dispatch Events') ?>
    </h2>

    <p class="border border-blue-300 bg-blue-100 p-4 rounded-md">
        <?= __('Will trigger a PHP "process" method who on his turn fires a browser event where is being listened to.') ?>
    </p>

    <div x-data="dispatchEventsDialog()" class="mt-4">
        <div x-show="isVisible()">
            <p class="border border-green-300 bg-green-100 p-4 rounded-md">
                <?= __('At this point the subsequent dispatched a process:after event set within the Magewire
                component. It also added a note to the finished list of todo\'s.') ?>
            </p>
        </div>
    </div>

    <button type="button" wire:click="process" class="btn btn-primary float-right">
        Toggle Process
    </button>
</div>

<script>
    function dispatchEventsDialog() {
        const self = this

        window.addEventListener('process:after', event => {
            self.visible = event.detail.show
        })

        return {
            visible: false,
            show() {
                self.visible = true
            },
            hide() {
                self.visible = false
            },
            isVisible() {
                return self.visible
            }
        }
    }
</script>
