<?php declare(strict_types=1);
/**
 * Copyright © Willem Poortman 2021-present. All rights reserved.
 *
 * Please read the README and LICENSE files for more
 * details on copyrights and license information.
 */

/** @var \Magewirephp\MagewireExamples\Magewire\Reacticon $magewire */
$magewire = $block->getMagewire();
?>
<div id="reacticon" class="space-y-4">
    <h2 class="text-xl font-bold mb-3 pb-2 border-b">
        Reacticon
    </h2>

    <div class="flex justify-between items-center"
         x-data="{
             increment: <?= $magewire->getIncrement() ? 'true' : 'false' ?>,
             decrement: <?= $magewire->getDecrement() ? 'true' : 'false' ?>
         }"
    >
        <button class="btn btn-primary bg-green-500 hover:bg-green-700 disabled:opacity-25"
                wire:click="increment"
                x-on:toggle-button.window="'increment' in $event.detail ? increment = $event.detail.increment"
                :disabled="!increment"
        >
            <span>&plus;<?= $magewire->getInterval() ?></span>
        </button>

        <div class="border border-gray-500 px-4 py-2 rounded-md">
            <?= $magewire->getQuantity() ?>
        </div>

        <button class="btn btn-primary bg-yellow-500 hover:bg-yellow-700 disabled:opacity-25"
                wire:click="decrement"
                x-on:toggle-button.window="'decrement' in $event.detail ? decrement = $event.detail.decrement"
                :disabled="!decrement"
        >
            <span>&minus;<?= $magewire->getInterval() ?></span>
        </button>
    </div>

    <div x-data="{explanationVisible: <?= !$magewire->getMarkAsDone() ? 'false' : 'true' ?>}"
         class="flex-col space-y-4"
    >
        <label class="inline-flex items-center cursor-pointer" for="showReacticonConfiguration">
            <input type="checkbox" id="showReacticonConfiguration" x-on:click="explanationVisible = !explanationVisible"/>
            <span class="ml-4">Show configuration</span>
        </label>

        <div class="border border-gray-300 bg-gray-100 p-4 rounded-md space-y-4" x-show="explanationVisible">
            <div class="flex items-center">
                <label for="quantity" class="inline-block w-20 mr-6 text-right font-bold text-gray-600">
                    <?= __('Interval') ?>
                </label>

                <input type="number"
                       id="quantity"
                       placeholder="number"
                       class="form-input flex-1 outline-none"
                       wire:model="interval"
                />
            </div>

            <div class="flex items-center">
                <label for="quantity" class="block w-20 mr-6 text-right font-bold text-gray-600">
                    <?= __('Increment') ?>
                </label>

                <input type="checkbox" id="quantity" wire:model="increment"/>
            </div>

            <div class="flex items-center">
                <label for="quantity" class="inline-block w-20 mr-6 text-right font-bold text-gray-600">
                    <?= __('Decrement') ?>
                </label>

                <input type="checkbox" id="quantity" wire:model="decrement"/>
            </div>
        </div>
    </div>

    <p class="border border-blue-300 bg-blue-100 p-4 rounded-md">
        <?= __('This example was used during my Magewire presentation at Reacticon V4. Go check it out on %1 if you
        missed it.', ['<a href="https://www.youtube.com/user/yireocom" target="_blank">YouTube</a>']) ?>
    </p>
</div>
