<?php declare(strict_types=1);
/**
 * Copyright © Willem Poortman 2021-present. All rights reserved.
 *
 * Please read the README and LICENSE files for more
 * details on copyrights and license information.
 */

/** @var \Magewirephp\MagewireExamples\Magewire\Todo $magewire */
$magewire = $block->getMagewire();
?>
<div id="wireable">
    <h2 class="text-xl font-bold mb-3 pb-2 border-b">
        Wireable
    </h2>

    <div class="space-y-6">
        <button type="button"
                class="btn btn-primary text-center w-full mb-6"
                wire:click="$set('settings.bar', 'foo')">
            Set 'bar' onto 'settings'
        </button>

        <input type="text" wire:model="settings.foo" class="block"/>
        <input type="text" wire:model="settings.bar" class="block"/>
    </div>
</div>
