<?php declare(strict_types=1);
/**
 * Copyright © Willem Poortman 2021-present. All rights reserved.
 *
 * Please read the README and LICENSE files for more
 * details on copyrights and license information.
 */

/** @var \Magewirephp\MagewireExamples\Magewire\Features\MagicActionsProperties\Specific $magewire */
$magewire = $block->getMagewire();
?>
<div id="magic-actions-properties" class="p-4 bg-gray-100">
    <h2 class="text-xl font-bold mb-3 pb-2 border-b">
        <?= __('Child Block: Emit Specific') ?>
    </h2>

    <div class="bg-gray-200 block p-4">
        Global emit was triggered: <?= $magewire->getGlobal() ? 'true' : 'false' ?>
    </div>
    <div class="bg-gray-200 block p-4">
        Specific emit was triggered: <?= $magewire->getSpecific() ? 'true' : 'false' ?>
    </div>
</div>
